### ISSUE TITLE
panic, probably on disconnect of client

### ISSUE THREAD

**Issue by piecegift** [creachadair/jrpc2#17] opened 2020-06-03 13:34 UTC
This happens after about a day of perfect work. I had 2 clients connected to the server. I used Loop function.

```
[jrpc2.Server] 2020/06/03 07:46:13 server.go:469: Received 1 new requests
[jrpc2.Server] 2020/06/03 07:46:13 server.go:469: Received 1 new requests
[jrpc2.Server] 2020/06/03 07:46:13 server.go:405: Server signaled to stop with err=EOF
[jrpc2.Server] 2020/06/03 07:46:13 server.go:165: Processing 1 requests
[jrpc2.Server] 2020/06/03 07:46:13 server.go:223: Checking request for "xxx.yyy": [42]
[jrpc2.Server] 2020/06/03 07:46:13 server.go:136: Reading next request: EOF
[jrpc2.Server] 2020/06/03 07:46:13 server.go:204: Completed 1 requests [850.11µs elapsed]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x56f841]

goroutine 50943 [running]:
github.com/creachadair/jrpc2.encode(0x0, 0x0, 0xc000ad2248, 0x1, 0x1, 0x1, 0x0, 0x1)
        /home/user/go/src/github.com/creachadair/jrpc2/base.go:362 +0x91
github.com/creachadair/jrpc2.(*Server).deliver(0xc000181520, 0xc000ad2248, 0x1, 0x1, 0x0, 0x0, 0xcf8be, 0x0, 0x0)
        /home/user/go/src/github.com/creachadair/jrpc2/server.go:213 +0x2ac
github.com/creachadair/jrpc2.(*Server).dispatch.func2(0x0, 0xc000020220)
        /home/user/go/src/github.com/creachadair/jrpc2/server.go:194 +0x123
github.com/creachadair/jrpc2.(*Server).serve.func1(0xc000181520, 0xc000545a40)
        /home/user/go/src/github.com/creachadair/jrpc2/server.go:142 +0x51
created by github.com/creachadair/jrpc2.(*Server).serve
        /home/user/go/src/github.com/creachadair/jrpc2/server.go:140 +0x6d
exit status 2
```

It looks `ch` is nil and was set by `stop`. I read the code and failed to figure out how it it possible that `ch` is nil and `s.inq.Len() > 0`. (If `s.inq.Len() == 0` then [nextRequest](https://github.com/creachadair/jrpc2/blob/9d3644745e72c615c8168c2959d47cd401c6258c/server.go#L159) would catch it.

**Comment by creachadair** [comment] 2020-06-04 17:00
Thanks for the report. Do you have a small example program that you could share, that reproduces the above failure?

**Comment by creachadair** [comment] 2020-07-21 18:28
I have not been able to reproduce this crash. I wrote a program that uses `server.Loop` with a large number of concurrent clients making multiple requests against that server, and tried it against both HEAD and v0.8.2. 

Since I was not able to reproduce the problem I am going to close this issue, but if you are still seeing the problem please feel free to re-open it with more details. I would be specifically interested to know what version of the library you're using, and if you can point to some example code that triggers the failure (even if it's not self-contained).

**Closed by creachadair** 2020-07-21 18:28 UTC
Labels: bug
